version: '2'

services:

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    links:
      - node:node
      # - node2:node2
      # - node3:node3
    depends_on:
      - node
      # - node2
      # - node3
    ports:
      - "8080:80"
    networks:
      - app-network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - app-network

  # node2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "3000"
  #   environment:
  #     - INSTANCE=node2
  #   networks:
  #     - app-network

  # node3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "3000"
  #   environment:
  #     - INSTANCE=node3
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
